#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_I2C_PRESENT
#define SL_CATALOG_I2C_I2C0_PRESENT
#define SL_CATALOG_I2C_I2C2_PRESENT
#define SL_CATALOG_SL_MAIN_PRESENT

#endif // SL_COMPONENT_CATALOG_H
